version: "3.3"

volumes:
  qb-redis: 
    external: true

services: 
  api:
    build: .
    environment:
      - STENO_REDIS_ADDR=redis:6379
    ports: 
      - "8080:8080"
  redis:
    image: redis
    volumes: 
      - qb-redis:/data

